services:
  deploy_registry:
    image: ${REGISTRY_HOST}/deploy-registry
    build:
      context: ../src
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=deploy-registry
      cache_to:
        - type=gha,scope=deploy-registry,mode=max
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - 7000:7000
    environment:
      DOCKER_HOSTS: unix:///var/run/docker.sock
      OTEL_LOG_LEVEL: debug
      OTEL_TRACES_EXPORTER: console,otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel.next/
